apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app
        tier: backend
    spec:
      containers:
        - name: app
          image: app
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: app
